### ISSUE TITLE
Z-fighting with litematica

### ISSUE THREAD

**Issue by supsm** [grondag/canvas#170]
The Litematica overlay experiences z-fighting with existing blocks. I don't see an issue pointing this out in the litematica issues, so I'm pretty sure it is only with canvas. (Haven't had time to test vanilla yet)

![2020-12-21_11 29 16](https://user-images.githubusercontent.com/60897356/102814628-c7631880-437f-11eb-92a1-58367530f12f.png)
![2020-12-21_11 29 10](https://user-images.githubusercontent.com/60897356/102814635-c92cdc00-437f-11eb-863a-8fbcbdf51584.png)

**Comment by grondag** [comment]
Does the problem go away if you turn off Batched Chunk Render in the Canvas config menu?

**Comment by grondag** [comment]
I'm guessing this may be the same root cause as #132

**Comment by supsm** [comment]
There is still z-fighting on the blocks on the ground, though the ones on the wall and ceiling are fixed.
Also I think turning it off is a bit bugged...
![2020-12-21_13 39 57](https://user-images.githubusercontent.com/60897356/102824605-0bf7af80-4392-11eb-8cac-75fb46e38b97.png)

**Comment by supsm** [comment]
Nevermind, the chunks wouldn't load unless I disconnect then rejoin.

**Comment by Nicolas-GE** [comment]
i have `renderBlocksAsTranslucent` enabled and don't have as much of an issue as far as i can see, but i still have a bit of z-fighting on things like chests on glass
![huge_2021-07-16_09 32 20](https://user-images.githubusercontent.com/42648527/125910120-2c46acb2-89d5-465b-9ad3-a5e13d25e966.png)
