### ISSUE TITLE
Bloom doesn't render on ReplayMod camera

### ISSUE THREAD

**Issue by SteveKunG** [grondag/canvas#345]
**System Information**

- Minecraft Version: 1.17.1
- Canvas Version: 1.0.2201
- Operating System: Windows 10
- Graphics Card: GTX 1050 Ti

**Other mods and versions installed**

![image](https://user-images.githubusercontent.com/6128413/142716412-81da88fa-b3ae-4813-9383-86ba14089d1d.png)

**How you triggered the behavior**

- Record replay in singleplayer for a minute
- Go to replay viewer and load them
- Look at block or item that emits the bloom effect

**What you expected would happen**

- Bloom should rendered on ReplayMod camera

**What actually happened**

- Bloom does not render at all

**Logs and screenshots**
- Canvas
![2021-11-20_13 04 17](https://user-images.githubusercontent.com/6128413/142716454-6972bc9f-eb70-49b7-937b-0c56e960991a.png)
- ReplayMod camera with Canvas
![2021-11-20_13 07 28](https://user-images.githubusercontent.com/6128413/142716472-d8c6e3d0-b038-4d68-9db3-6be881b38055.png)

- Canvas
![2021-11-20_13 04 21](https://user-images.githubusercontent.com/6128413/142716456-45e76122-fb49-4128-9c8d-cd61c7f6a585.png)
- ReplayMod camera with Canvas
![2021-11-20_13 03 46](https://user-images.githubusercontent.com/6128413/142716476-2a25e195-c97d-4b80-8daa-26c414aa0609.png)

**Comment by supsm** [comment]
This also happens in tweakeroo freecam, I suspect it is the same issue but it probably easier to reproduce as it can be easily toggled on and off.

**Comment by spiralhalo** [comment]
Should be fixed https://github.com/vram-guild/canvas/commit/cc8483c32b03d1853f7d9b92b6b002b5bb6406a9

**Comment by supsm** [comment]
This does not appear to be fixed, forget-me-not is still having issues

**Comment by spiralhalo** [comment]
Can't reproduce. fmn latest commit works fine both in editing and render. What minecraft version are you using?

https://user-images.githubusercontent.com/8444172/184521194-22f4aa4d-17b9-4f99-a0cc-9f75c9e3ffee.mp4

**Comment by supsm** [comment]
1.18.2, canvas 1.0.2397  
I thought the fixes were backported to 1.18 but I guess not?

**Comment by spiralhalo** [comment]
Apparently not. Pushed the backport. Thanks for the report 👍
