### ISSUE TITLE
Resource Pack Selection Screen Causes Massive VRAM Leak WITH Respack Opts mod

### ISSUE THREAD

**Issue by heymanMC** [grondag/canvas#352]
**System Informatinon**

- Minecraft Version: 1.18.1
- Canvas Version: 1.0.2256
- Operating System: Windows 10
- Graphics Card: NVIDIA RTX 3080

**Other mods and versions installed**
- Respack Opts v2.9.0
https://www.curseforge.com/minecraft/mc-mods/respackopts
- Fabric API (required for Respack Opts) v0.44.0+1.18

**How you triggered the behavior**

1. Install Canvas, Fabric API, and Respack Opts
2. Open "Resource Packs" selection screen
**What you expected would happen**
I would expect this screen not to leak all my memory.

**What actually happened**

MC eats all my GPU's VRAM in seconds.

**Logs and screenshots**
- Logs: https://paste.ee/p/IHnHq
- Video:
    - Download: https://cdn.discordapp.com/attachments/614625541114298397/920155293030182922/Base_Profile_2021.12.13_-_20.26.47.02.mp4
    - Directly on discord: https://discord.com/channels/614624415631671316/614625541114298397/920155296528216085
    - Watch the mouse. All I do is open MC, then the resource pack selection screen. Watch as the VRAM climbs to full.

**Note:**
This does not happen with each mod separately. It only happens when *both* are installed together.

**Comment by JFronny** [comment]
Respackopts saves configs whenever resources are reloaded. The pack screen registers that files in the resource pack directory (the config files for packs) have changed, causing a resource reload. This led to an infinite loop of reloading resources, exposing some memory leak elsewhere. The infinite reloading has been fixed in the latest commit.

**Comment by heymanMC** [comment]
Thanks.
Fixed via https://gitlab.com/jfmods/respackopts/-/commit/cd18b5d85f5ef998602a2e8421a17776309f29b3

**Comment by coderbot16** [comment]
Sounds like this isn't actually fixed - just the memory leak is much slower now...

**Comment by JFronny** [comment]
Yes, the only thing I fixed was the resource reloading loop

**Comment by supsm** [comment]
@JFronny can you release to curseforge?
